name: ICU_predict
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - numpy=1.26.0
  - pandas=2.1.3
  - scikit-learn=1.3.0
  - ipykernel=6.25.0
  - matplotlib=3.8.2
  - seaborn=0.12.2
  - lifelines=0.27.8
  - Jinja2=3.1.2
